### ISSUE TITLE
Analysis: Return axes object when using plotting functions

### ISSUE THREAD

**Issue by lcdumort** [mfgustavo/glompo#9]
Maybe it could be useful to have the ability to pass an `axes` object when using one of the plotting functions in the `glompo.analysis` functionalities. This would give the user the ability to further edit/refine the figures with matplotlib.

**Comment by mfgustavo** [comment]
This is a good idea. I have been wanted to implement something like this so that EstimatedEffects can be used interactively in a Jupyter notebook where you try different things and take different views on the data. There are some problems though, do you have any suggestions:
1) Some functions produce multiple plots depending on the indices chosen etc. What should be returned in that case?
2) There are two user types: ones who will call the plot methods and expect something to save, and ones who would like a return (to edit it or see it in Jupyter). What is the smoothest interface to cater to both? My idea is to make `path` default to None (returning the axis) but if it is provided then the plot is saved and nothing is returned.

**Comment by lcdumort** [comment]
What I would do is let the user manually generate the ```axes``` object, and use that ```axes``` in the rest of plotting function.

How I think it would be useful in, for example, a jupyter notebook:
```python
ee = EstimatedEffects(args)

fig, ax = plt.subplots()
ee.plot_sensitivities(axes=ax)
```
after which the ax object contains the sensitivities plot. You wouldn't really return anything here either, you would just alter the ax object that has been provided.

Whenever a user does not provide an axes or sets a ```path``` argument, you could the function let it proceed as it does right now. I haven't thoroughly looked in your source code, but for example here:
https://github.com/mfgustavo/glompo/blob/4186039af36670dffb0db37337ca6fe0a3015127/glompo/analysis/estimatedeffects.py#L914-L915

would then just be changed to
```python
if not ax:
    fig, ax = plt.subplots()
```

And likewise at 
https://github.com/mfgustavo/glompo/blob/4186039af36670dffb0db37337ca6fe0a3015127/glompo/analysis/estimatedeffects.py#L950-L953

```python
if not ax:
     fig.tight_layout() 
     fig.savefig(path, transparent=False, facecolor='white') 
     
    plt.close(fig) 
```
assuming that the ```ax``` argument defaults to ```None``` offcourse.

Anyway just an idea on how I would do it, I'm not sure if it is the most pythonic way to do so. It is however similar to the pandas plotting functions, which is where I got the idea a bit

**Comment by lcdumort** [comment]
And for the question when multiple plots are generated: Maybe it is a possibility to just pass an array of axes to that function, but proceed similarly like the example above? You can easily generate multiple axes like this:
```python
fig, axes = plt.subplots(3,1)
axes = axes.flatten()
```

**Comment by mfgustavo** [comment]
This should now be addressed well. All functions return a Figure or list of Figures from which you can extract the axes and make changes. All plot functions will also display images inline in a Jupyter setting and saving is optional.
